package com.joefrew.neuralnet.old;

/**
 * The bias input class is used with the bias neuron. It implements neural input so it can be used
 * as an input to a neuron and weighted so that its weights can be generated by a weight generator.
 * @author joe
 *
 */
public class BiasInput implements NeuralInput, Weighted {
	
	private double weight;
	
	public BiasInput(double weight) {
		this.weight = weight;
	}
	
	public void setWeight(double newWeight) {
		this.weight = newWeight;
	}

	public double getInput() {
		return weight;
	}

	public double getWeight() {
		return weight;
	}

}
